inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'spec/**/*'
    - 'script/*'
    - 'features/**/*'
RSpec/ScatteredSetup:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '*.gemspec'
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/ApplicationRecord:
  Enabled: false
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Naming/FileName:
  Exclude:
    - 'Appraisals'
    - 'Gemfile'
Metrics/CyclomaticComplexity:
  Exclude:
# catalog_controller.rb is usually long because it is mostly configuration
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/workspace_controller.rb'
