#!/bin/bash

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

rvm use ruby-2.1.5 || exit 100
rvm use ruby-2.1.5@build --create || exit 100

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

case $1 in
patch)
    ;;
install_deps)
    git submodule init
    git submodule update
    ;;
configure)

rvm --force gemset empty ruby-2.1.5@build || exit 100

cp config/jetty.yml.sample config/jetty.yml
cp config/fedora.yml.sample config/fedora.yml
cp config/solr.yml.sample config/solr.yml
cp config/database.yml.sample config/database.yml
cp config/redis.yml.sample config/redis.yml
#cp config/doi.yml.sample config/doi.yml

cat > config/settings.local.yml << __EOF__
interface:
  languages: [en, ga]
dri:
  files: dri_files
plugins:
  ffmpeg_path: /usr/bin/ffmpeg
S3:
  server: http://objects.dri.ie
  access_key_id: OMZPBA7D6U3MZ6MBVJZQ
  secret_access_key: nnXKfE/+0zfEsHW8n55ffP18Bvn+N9sJ83AmWPOS
  bucket_prefix: buildbot
__EOF__

    bundle install --quiet
    bundle exec rake db:migrate
    bundle exec rake db:seed
    bundle exec rake db:migrate
    bundle exec rake db:test:prepare
    bundle exec rake dri:fixtures:generate
    ;;
compile)
    ;;
check)
    bundle exec rake ci_spec || exit 100
    bundle exec rake db:migrate
    bundle exec rake db:seed
    bundle exec rake dri:fixtures:generate
    bundle exec rake db:test:prepare
    bundle exec rake ci || exit 100
    bundle exec rake rdoc
    bundle exec rake assets:precompile
    ;;
package)
    ;;
upload)
    if [[ -s "$HOME/hosts.buildbot" ]] ; then
      cp $HOME/hosts.buildbot deploy/hosts.buildbot
      #if [[ "$branch" == "master" ]]; then
        #ansible-playbook -i deploy/hosts.buildbot deploy/playbooks/setup-dri_app-nuig-rnag.yml -e "deploy_branch=$(git rev-parse HEAD)"
      #fi
    else
      printf "Can't upload and deploy, can't find hosts.buildbot file"
    fi
    ;;
compile_extra)
    #curl http://repository.dri.ie/v1 > /dev/null 2>&1
    ;;
uninstall_deps)
    ;;
esac
